.define _XBINDX .byte $00,$28
.define _XCOSCR .byte $00,$34
.define _XCRLF .byte $00,$25
.define _XCSSCR .byte $00,$35
.define _XDECIM .byte $00,$29
.define _XDIVIS .byte $00,$23
.define _XGOKBD .byte $00,$52
.define _XHEXA .byte $00,$2A
.define _XINSER .byte $00,$2E
.define _XMULT .byte $00,$21
.define _XRD0 .byte $00,$08
.define _XRDW0 .byte $00,$0C
.define _XTSTBU .byte $00,$56
.define _XWR0 .byte $00,$10
.define _XWR1 .byte $00,$11
.define _XWSTR0 .byte $00,$14
.define _XWSTR1 .byte $00,$15


.define KEY_CTRL_C $03
.define KEY_ESC $1B


.define MNTL_ANNULATION $A4
.define MNTL_CORRECTION $A6
.define MNTL_ENVOI $A0
.define MNTL_RETOUR $A1
.define MNTL_SOMMAIRE $A5
.define MNTL_SUITE $A7


.define I_JMP $4C
